version: '3.8'
services:
  postgres:
    image: postgres
    ports:
      - 5445:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: crud-db
    expose:
      - 5445
